language: csharp

os:
  - linux
  - osx

mono:
  - latest
  - 4.8.0

sudo: false

script:
  - ./build.sh

#  matrix:
#  exclude:
#    - os: osx
#      mono: 4.4.2
#    - os: osx
#      mono: 4.8.0
#
#  allow_failures:
#    - os: osx
#      mono: latest
#    - os: linux
#      mono: latest
#    - os: linux
#      mono: 4.8.0
#    - os: osx
#      mono: latest

